/*
 * Generated by Bluespec Compiler, version 2019.05.beta2 (build a88bf40db, 2019-05-24)
 * 
 * On Mon Feb  3 21:31:08 GMT 2020
 * 
 */
#ifndef __vpi_wrapper_c_trygetchar_h__
#define __vpi_wrapper_c_trygetchar_h__

#include <vpi_user.h>

/* registration function */
void c_trygetchar_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_trygetchar_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_trygetchar_h__ */
